apiVersion: v1
kind: Service
metadata:
  name: nginx-log-ingestion
  namespace: observability
  annotations:
    # Uncomment to make it INTERNAL only
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx-log-ingestion
  ports:
  - name: https
    port: 443
    targetPort: 443
